# compose spec doesn't need a version anymore,
# see https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:
  # traefik container 
  traefik:
    image: traefik:v3.0
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`yaroslavtanko.dev`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=httpchallenge"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$9v4lPqGe$$8HLykKRYKi9Ev6.2mHPaj1"

  # whoami example container
  whoami:
    image: traefik/whoami
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.yaroslavtanko.dev`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=httpchallenge"

networks:
  traefik-servicenet:
    external: true
    name:
      traefik-servicenet # create this network before running this deployment:
      # docker network create traefik-servicenet
